const ROWS=['あいうえお','かきくけこ','さしすせそ','たちつてと','なにぬねの','はひふへほ','まみむめも','や　ゆ　よ','らりるれろ','わ　　をん'];
const $=s=>document.querySelector(s),guide=$('#guide'),ink=$('#ink'),g=guide.getContext('2d'),c=ink.getContext('2d');
let mode='hira',letter='あ',repeat=0,stroke=0,routes=[],drawing=false,progress=0,last=null,done=false,holder=null,committedInk=null,visited=null,specialDistance=0,thirdMistakes=0,thirdAssist=false,advanceTimer=null,runId=0,offRoute=0,audioContext=null;
const completionKey='kana-tracing-completed-v1';
let completions=[];
try{completions=JSON.parse(localStorage.getItem(completionKey)||'[]');if(!Array.isArray(completions))completions=[]}catch{completions=[]}
function saveCompletions(){localStorage.setItem(completionKey,JSON.stringify(completions));$('#undo').hidden=!completions.length;$('#clearAll').hidden=!completions.length;grid()}
function kana(ch){let n=ch.codePointAt(0);return mode==='kata'&&n>=0x3041&&n<=0x3096?String.fromCodePoint(n+0x60):ch}
function grid(){$('#grid').replaceChildren(...ROWS.map(row=>{let col=document.createElement('div');col.className='kana-column';for(let ch of row){if(ch==='　'){col.append(document.createElement('span'));continue}let b=document.createElement('button');b.className='cell';let character=kana(ch);b.textContent=character;if(completions.some(v=>v.mode===mode&&v.letter===character)){let mark=document.createElement('span');mark.className='ok-mark';mark.textContent='OK';b.append(mark);b.setAttribute('aria-label',character+' OK')}b.onclick=()=>start(character);col.append(b)}return col}))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));grid()});grid();
$('#undo').hidden=!completions.length;
$('#clearAll').hidden=!completions.length;
$('#undo').onclick=()=>{if(!completions.length)return;completions.pop();saveCompletions()};
$('#clearAll').onclick=()=>{completions=[];saveCompletions()};
function cancelAdvance(){clearTimeout(advanceTimer);advanceTimer=null;runId++}
$('#back').onclick=()=>{cancelAdvance();$('#practice').hidden=true;$('#picker').hidden=false;$('#back').hidden=true;holder?.remove()};
$('#reset').onclick=()=>{cancelAdvance();stroke=0;render(false)};
function advance(){if(stroke<routes.length)return;repeat++;stroke=0;if(repeat===3){$('#practice').hidden=true;$('#picker').hidden=false;$('#back').hidden=true;holder?.remove()}else{thirdMistakes=0;thirdAssist=false;render(false)}}
async function start(ch){cancelAdvance();letter=ch;repeat=0;stroke=0;thirdMistakes=0;thirdAssist=false;done=false;$('#picker').hidden=true;$('#practice').hidden=false;$('#back').hidden=false;$('#reset').hidden=false;$('#prompt').textContent=letter+' を なぞろう';$('#message').textContent='おてほんを よみこんでいます';
 try{let source=window.STROKE_SVGS[mode==='hira'?'hiragana':'katakana'][ch];if(!source)throw Error('missing');let svg=new DOMParser().parseFromString(source,'image/svg+xml').documentElement;holder?.remove();holder=document.createElement('div');holder.style.cssText='position:absolute;left:-9999px;top:0;width:1024px;height:1024px;opacity:0;pointer-events:none';holder.append(document.importNode(svg,true));document.body.append(holder);let root=holder.querySelector('svg'),strokes=root.querySelector('[data-strokesvg="strokes"]'),shadows=root.querySelector('[data-strokesvg="shadows"]');
 routes=[...strokes.children].map((child,i)=>{let path=child.tagName.toLowerCase()==='path'?child:child.querySelector('path'),shadow=shadows.children[i],shapes=shadow.tagName.toLowerCase()==='path'?[shadow]:[...shadow.querySelectorAll('path')],fills=shapes.map(p=>new Path2D(p.getAttribute('d'))),len=path.getTotalLength(),samples=[];for(let d=0;d<=len;d+=6){let p=path.getPointAtLength(d);if(fills.some(f=>g.isPointInPath(f,p.x,p.y)))samples.push({x:p.x*600/1024,y:p.y*600/1024})}if(samples.length<2)throw Error('empty stroke');return samples});render(false)}catch(err){$('#message').textContent='おてほんを よみこめませんでした。ページを ひらきなおしてね';console.error(err)}}
function simplify(points,tolerance){const sq=tolerance*tolerance;function segment(a,b){let best=0,index=-1,dx=points[b].x-points[a].x,dy=points[b].y-points[a].y,den=dx*dx+dy*dy;for(let i=a+1;i<b;i++){let t=den?Math.max(0,Math.min(1,((points[i].x-points[a].x)*dx+(points[i].y-points[a].y)*dy)/den)):0,x=points[a].x+t*dx,y=points[a].y+t*dy,d=(points[i].x-x)**2+(points[i].y-y)**2;if(d>best){best=d;index=i}}if(best>sq){segment(a,index);out.push(points[index]);segment(index,b)}}let out=[points[0]];segment(0,points.length-1);out.push(points.at(-1));return out}
function resample(points,spacing){let out=[points[0]];for(let i=1;i<points.length;i++){let a=points[i-1],b=points[i],n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/spacing));for(let j=1;j<=n;j++)out.push({x:a.x+(b.x-a.x)*j/n,y:a.y+(b.y-a.y)*j/n})}return out}
function line(ctx,ps,color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(ps[0].x,ps[0].y);for(let p of ps.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke()}
function prepareAudio(){try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume()}catch{}}
function celebrate(){prepareAudio();if(audioContext){[0,.12,.24].forEach((delay,i)=>{let oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),at=audioContext.currentTime+delay;oscillator.type='sine';oscillator.frequency.value=[523,659,784][i];gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(.14,at+.015);gain.gain.exponentialRampToValueAtTime(.0001,at+.24);oscillator.connect(gain).connect(audioContext.destination);oscillator.start(at);oscillator.stop(at+.25)})}let stage=$('#confetti');if(!stage)return;stage.replaceChildren();for(let i=0;i<42;i++){let piece=document.createElement('i');piece.style.setProperty('--x',(Math.random()*100)+'%');piece.style.setProperty('--dx',((Math.random()-.5)*200)+'px');piece.style.setProperty('--delay',(Math.random()*.18)+'s');piece.style.setProperty('--color',['#e8a85d','#77bdac','#e67f87','#a4a4e7','#59bfe8'][i%5]);stage.append(piece)}setTimeout(()=>stage.replaceChildren(),1800)}
function showAssist(){return repeat<2||thirdAssist}
function render(keepInk=false){done=false;drawing=false;progress=0;last=null;visited=null;$('#next').hidden=true;$('#reset').hidden=false;$('#phase').textContent='ひらがな・カタカナ';$('#prompt').textContent=letter+' を なぞろう';$('#count').textContent=(repeat+1)+' / 3 かい';$('#progress').replaceChildren(...Array.from({length:3},(_,i)=>{let d=document.createElement('span');d.className='dot '+(i<repeat?'done':i===repeat?'now':'');return d}));g.clearRect(0,0,600,600);if(!keepInk){c.clearRect(0,0,600,600);committedInk=null}g.fillStyle='#fff';g.fillRect(0,0,600,600);g.setLineDash([9,10]);g.strokeStyle='#e5ebe5';g.lineWidth=2;g.beginPath();g.moveTo(300,24);g.lineTo(300,576);g.moveTo(24,300);g.lineTo(576,300);g.stroke();g.setLineDash([]);routes.forEach((p,i)=>{if(i>=stroke)line(g,p,i===stroke&&showAssist()?'#edb874':'#d6ded8',i===stroke&&showAssist()?31:27)});
 if(stroke<routes.length){if(showAssist()){let p=routes[stroke][0];g.fillStyle='#e86b46';g.beginPath();g.arc(p.x,p.y,15,0,Math.PI*2);g.fill();g.fillStyle='#fff';g.font='bold 17px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(String(stroke+1),p.x,p.y+1)}$('#message').textContent=showAssist()?(stroke+1)+' かくめ。オレンジの てんから はじめてね':(stroke+1)+' かくめ。じぶんで かいてみよう'}else{done=true;$('#message').textContent='じょうず！';if(repeat===2){completions=completions.filter(v=>!(v.mode===mode&&v.letter===letter));completions.push({mode,letter});saveCompletions()}let id=runId;advanceTimer=setTimeout(()=>{if(id===runId)advance()},900);try{celebrate()}catch(err){console.warn('celebration skipped',err)}}}
function pos(e){let r=ink.getBoundingClientRect();return{x:(e.clientX-r.left)*600/r.width,y:(e.clientY-r.top)*600/r.height}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function fail(reason,countMistake=true){drawing=false;if(committedInk)c.putImageData(committedInk,0,0);else c.clearRect(0,0,600,600);progress=0;last=null;visited=null;offRoute=0;if(repeat===2&&!thirdAssist&&countMistake){thirdMistakes++;if(thirdMistakes>=3){thirdAssist=true;render(true);$('#message').textContent='3かい まちがえたので、おてほんを だしたよ';return}}$('#message').textContent=reason+'。この かくの はじめから もういちど';navigator.vibrate?.(65)}
function relaxedStroke(){return mode==='hira'&&stroke===1&&['わ','れ','ね'].includes(letter)}
function markVisited(q,route){let nearest=Infinity;for(let i=0;i<route.length;i++){let d=dist(q,route[i]);if(d<nearest)nearest=d;if(d<=65)visited[i]=1}return nearest}
ink.onpointerdown=e=>{prepareAudio();if(done||!routes.length)return;let p=pos(e),route=routes[stroke],startLimit=relaxedStroke()?95:showAssist()?72:85;if(dist(p,route[0])>startLimit){fail(showAssist()?'オレンジの てんから はじめてね':'かきはじめの ばしょが ちがうよ');return}ink.setPointerCapture(e.pointerId);drawing=true;progress=0;last=p;offRoute=0;if(relaxedStroke()){visited=new Uint8Array(route.length);specialDistance=0;markVisited(p,route)}$('#message').textContent='せんに そって すすもう'};
ink.onpointermove=e=>{if(!drawing)return;let p=pos(e),route=routes[stroke],length=dist(last,p),steps=Math.max(1,Math.ceil(length/5)),relax=relaxedStroke();if(relax)specialDistance+=length;for(let k=1;k<=steps;k++){let q={x:last.x+(p.x-last.x)*k/steps,y:last.y+(p.y-last.y)*k/steps};if(relax){markVisited(q,route);continue}let best=-1,score=Infinity;for(let i=Math.max(0,progress-5);i<Math.min(route.length,progress+22);i++){let d=dist(q,route[i]);if(d<score){score=d;best=i}}if(score>62){offRoute+=length/steps;if(offRoute>38){fail('せんから はみでたよ');return}}else{offRoute=0;progress=Math.max(progress,best)}}line(c,[last,p],'#348c78',20);last=p};
ink.onpointerup=()=>{if(!drawing)return;drawing=false;let route=routes[stroke],complete;if(relaxedStroke()){let count=visited.reduce((a,b)=>a+b,0),routeLength=route.slice(1).reduce((sum,p,i)=>sum+dist(p,route[i]),0);complete=count/visited.length>=0.28&&specialDistance>=routeLength*0.23&&dist(last,route.at(-1))<155}else complete=progress/Math.max(1,route.length-1)>=0.68&&dist(last,route.at(-1))<110;if(!complete){fail('さいごまで なぞってね');return}committedInk=c.getImageData(0,0,600,600);stroke++;render(true)};
ink.onpointercancel=()=>{if(drawing)fail('もういちど なぞってね',false)};
